// Generated by CIRCT firtool-1.62.0
module BitShuffle(
  input  [3:0] io_in_0,
               io_in_1,
               io_in_2,
               io_in_3,
               io_in_4,
               io_in_5,
               io_in_6,
               io_in_7,
  output [7:0] io_out_0,
               io_out_1,
               io_out_2,
               io_out_3
);

  assign io_out_0 =
    {io_in_7[0],
     io_in_6[0],
     io_in_5[0],
     io_in_4[0],
     io_in_3[0],
     io_in_2[0],
     io_in_1[0],
     io_in_0[0]};
  assign io_out_1 =
    {io_in_7[1],
     io_in_6[1],
     io_in_5[1],
     io_in_4[1],
     io_in_3[1],
     io_in_2[1],
     io_in_1[1],
     io_in_0[1]};
  assign io_out_2 =
    {io_in_7[2],
     io_in_6[2],
     io_in_5[2],
     io_in_4[2],
     io_in_3[2],
     io_in_2[2],
     io_in_1[2],
     io_in_0[2]};
  assign io_out_3 =
    {io_in_7[3],
     io_in_6[3],
     io_in_5[3],
     io_in_4[3],
     io_in_3[3],
     io_in_2[3],
     io_in_1[3],
     io_in_0[3]};
endmodule

module BitShuffleWrapper(
  input  [31:0] io_in,
  output [31:0] io_out
);

  wire [7:0] _bitShuffle_io_out_0;
  wire [7:0] _bitShuffle_io_out_1;
  wire [7:0] _bitShuffle_io_out_2;
  wire [7:0] _bitShuffle_io_out_3;
  BitShuffle bitShuffle (
    .io_in_0  (io_in[3:0]),
    .io_in_1  (io_in[7:4]),
    .io_in_2  (io_in[11:8]),
    .io_in_3  (io_in[15:12]),
    .io_in_4  (io_in[19:16]),
    .io_in_5  (io_in[23:20]),
    .io_in_6  (io_in[27:24]),
    .io_in_7  (io_in[31:28]),
    .io_out_0 (_bitShuffle_io_out_0),
    .io_out_1 (_bitShuffle_io_out_1),
    .io_out_2 (_bitShuffle_io_out_2),
    .io_out_3 (_bitShuffle_io_out_3)
  );
  assign io_out =
    {_bitShuffle_io_out_3,
     _bitShuffle_io_out_2,
     _bitShuffle_io_out_1,
     _bitShuffle_io_out_0};
endmodule

module MyTest(
  input         clock,
                reset,
  input  [7:0]  io_HsrcId,
  input         io_stream_in_TVALID,
  input  [31:0] io_stream_in_TDATA,
  input  [3:0]  io_stream_in_TKEEP,
  input         io_stream_in_TLAST,
  output        io_stream_in_TREADY,
                io_stream_out_TVALID,
  output [31:0] io_stream_out_TDATA,
  output [3:0]  io_stream_out_TKEEP,
  output        io_stream_out_TLAST,
  input         io_stream_out_TREADY
);

  wire [31:0] _bitshuffle_io_out;
  reg         stateInReg;
  reg         stateOutReg;
  reg  [31:0] headerInReg;
  reg  [31:0] dataInReg;
  wire        _GEN = io_stream_out_TREADY & stateInReg;
  always @(posedge clock) begin
    if (reset) begin
      stateInReg <= 1'h0;
      stateOutReg <= 1'h0;
      headerInReg <= 32'h0;
      dataInReg <= 32'h0;
    end
    else begin
      if (stateInReg)
        stateInReg <= ~(stateInReg & ~stateOutReg & _GEN) & stateInReg;
      else
        stateInReg <= io_stream_in_TVALID | stateInReg;
      if (stateOutReg)
        stateOutReg <= ~(stateOutReg & io_stream_out_TREADY) & stateOutReg;
      else
        stateOutReg <= _GEN | stateOutReg;
      if (~stateInReg & io_stream_in_TVALID)
        headerInReg <= io_stream_in_TDATA;
      if (stateInReg & io_stream_in_TVALID)
        dataInReg <= io_stream_in_TDATA;
    end
  end // always @(posedge)
  BitShuffleWrapper bitshuffle (
    .io_in  (dataInReg),
    .io_out (_bitshuffle_io_out)
  );
  assign io_stream_in_TREADY = 1'h1;
  assign io_stream_out_TVALID = stateOutReg ? stateOutReg : _GEN;
  assign io_stream_out_TDATA =
    stateOutReg
      ? _bitshuffle_io_out
      : _GEN
          ? {headerInReg[31:24], io_HsrcId[5:0], headerInReg[17:6], headerInReg[23:18]}
          : 32'h0;
  assign io_stream_out_TKEEP = 4'hF;
  assign io_stream_out_TLAST = stateOutReg;
endmodule

